#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml
index:
  path: /index
  controller: App\Controller\ProductController::index
updatec:
  path: '/updatec'
  controller: App\Controller\CategorieController::updatec



